name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: permission
      run: chmod +x gradlew

    - name: Build and Deploy
      uses: msfjarvis/setup-android@1.0
      with:
        entrypoint: ./gradlew
        args: dependencies assembleDebug
